// Generated by CoffeeScript 1.3.3
(function() {

  describe("Toolchain test", function() {
    return it("should work properly", function() {
      return expect(1 + 1).toEqual(2);
    });
  });

}).call(this);
